<?php

namespace App\Support;

final class RomanianLocalityNames
{
    private const NAMES = [
        1883 => ['ascii' => 'Sebes', 'display' => 'Sebeș'],
        2924 => ['ascii' => 'Baia de Aries', 'display' => 'Baia de Arieș'],
        1464 => ['ascii' => 'Campeni', 'display' => 'Câmpeni'],
        1801 => ['ascii' => 'Ocna Mures', 'display' => 'Ocna Mureș'],
        8103 => ['ascii' => 'Teius', 'display' => 'Teiuș'],
        9468 => ['ascii' => 'Chisineu-Cris', 'display' => 'Chișineu-Criș'],
        9636 => ['ascii' => 'Nadlac', 'display' => 'Nădlac'],
        9663 => ['ascii' => 'Pancota', 'display' => 'Pâncota'],
        12108 => ['ascii' => 'Santana', 'display' => 'Sântana'],
        9707 => ['ascii' => 'Sebis', 'display' => 'Sebiș'],
        13506 => ['ascii' => 'Campulung', 'display' => 'Câmpulung'],
        13631 => ['ascii' => 'Curtea de Arges', 'display' => 'Curtea de Argeș'],
        13178 => ['ascii' => 'Pitesti', 'display' => 'Pitești'],
        13677 => ['ascii' => 'Costesti', 'display' => 'Costești'],
        13409 => ['ascii' => 'Stefanesti', 'display' => 'Ștefănești'],
        20304 => ['ascii' => 'Bacau', 'display' => 'Bacău'],
        20885 => ['ascii' => 'Moinesti', 'display' => 'Moinești'],
        20572 => ['ascii' => 'Onesti', 'display' => 'Onești'],
        20787 => ['ascii' => 'Buhusi', 'display' => 'Buhuși'],
        20830 => ['ascii' => 'Comanesti', 'display' => 'Comănești'],
        22175 => ['ascii' => 'Darmanesti', 'display' => 'Dărmănești'],
        20929 => ['ascii' => 'Slanic-Moldova', 'display' => 'Slănic-Moldova'],
        20974 => ['ascii' => 'Targu Ocna', 'display' => 'Târgu Ocna'],
        26813 => ['ascii' => 'Beius', 'display' => 'Beiuș'],
        26706 => ['ascii' => 'Alesd', 'display' => 'Aleșd'],
        30924 => ['ascii' => 'Sacueni', 'display' => 'Săcueni'],
        26859 => ['ascii' => 'Stei', 'display' => 'Ștei'],
        27016 => ['ascii' => 'Vascau', 'display' => 'Vașcău'],
        32401 => ['ascii' => 'Bistrita', 'display' => 'Bistrița'],
        32553 => ['ascii' => 'Nasaud', 'display' => 'Năsăud'],
        32606 => ['ascii' => 'Sangeorz-Bai', 'display' => 'Sângeorz-Băi'],
        35740 => ['ascii' => 'Botosani', 'display' => 'Botoșani'],
        37299 => ['ascii' => 'Flamanzi', 'display' => 'Flămânzi'],
        36079 => ['ascii' => 'Saveni', 'display' => 'Săveni'],
        39177 => ['ascii' => 'Stefanesti', 'display' => 'Ștefănești'],
        40205 => ['ascii' => 'Brasov', 'display' => 'Brașov'],
        40287 => ['ascii' => 'Fagaras', 'display' => 'Făgăraș'],
        40447 => ['ascii' => 'Sacele', 'display' => 'Săcele'],
        40376 => ['ascii' => 'Rasnov', 'display' => 'Râșnov'],
        40508 => ['ascii' => 'Zarnesti', 'display' => 'Zărnești'],
        42691 => ['ascii' => 'Braila', 'display' => 'Brăila'],
        42762 => ['ascii' => 'Faurei', 'display' => 'Făurei'],
        43420 => ['ascii' => 'Insuratei', 'display' => 'Însurăței'],
        44827 => ['ascii' => 'Buzau', 'display' => 'Buzău'],
        44854 => ['ascii' => 'Ramnicu Sarat', 'display' => 'Râmnicu Sărat'],
        48334 => ['ascii' => 'Patarlagele', 'display' => 'Pătârlagele'],
        51029 => ['ascii' => 'Caransebes', 'display' => 'Caransebeș'],
        50807 => ['ascii' => 'Resita', 'display' => 'Reșița'],
        50932 => ['ascii' => 'Baile Herculane', 'display' => 'Băile Herculane'],
        50978 => ['ascii' => 'Bocsa', 'display' => 'Bocșa'],
        51065 => ['ascii' => 'Moldova Noua', 'display' => 'Moldova Nouă'],
        51127 => ['ascii' => 'Oravita', 'display' => 'Oravița'],
        51216 => ['ascii' => 'Otelu Rosu', 'display' => 'Oțelu Roșu'],
        92578 => ['ascii' => 'Calarasi', 'display' => 'Călărași'],
        100629 => ['ascii' => 'Oltenita', 'display' => 'Oltenița'],
        101467 => ['ascii' => 'Budesti', 'display' => 'Budești'],
        55366 => ['ascii' => 'Campia Turzii', 'display' => 'Câmpia Turzii'],
        60428 => ['ascii' => 'Constanta', 'display' => 'Constanța'],
        62413 => ['ascii' => 'Baneasa', 'display' => 'Băneasa'],
        60785 => ['ascii' => 'Cernavoda', 'display' => 'Cernavodă'],
        60810 => ['ascii' => 'Harsova', 'display' => 'Hârșova'],
        60516 => ['ascii' => 'Navodari', 'display' => 'Năvodari'],
        62404 => ['ascii' => 'Negru Voda', 'display' => 'Negru Vodă'],
        63401 => ['ascii' => 'Sfantu Gheorghe', 'display' => 'Sfântu Gheorghe'],
        63759 => ['ascii' => 'Targu Secuiesc', 'display' => 'Târgu Secuiesc'],
        63599 => ['ascii' => 'Intorsura Buzaului', 'display' => 'Întorsura Buzăului'],
        65351 => ['ascii' => 'Targoviste', 'display' => 'Târgoviște'],
        65690 => ['ascii' => 'Gaesti', 'display' => 'Găești'],
        68636 => ['ascii' => 'Racari', 'display' => 'Răcari'],
        70325 => ['ascii' => 'Bailesti', 'display' => 'Băilești'],
        72016 => ['ascii' => 'Dabuleni', 'display' => 'Dăbuleni'],
        70423 => ['ascii' => 'Filiasi', 'display' => 'Filiași'],
        75105 => ['ascii' => 'Galati', 'display' => 'Galați'],
        75347 => ['ascii' => 'Beresti', 'display' => 'Berești'],
        75481 => ['ascii' => 'Targu Bujor', 'display' => 'Târgu Bujor'],
        104145 => ['ascii' => 'Mihailesti', 'display' => 'Mihăilești'],
        77821 => ['ascii' => 'Targu Jiu', 'display' => 'Târgu Jiu'],
        79317 => ['ascii' => 'Bumbesti-Jiu', 'display' => 'Bumbești-Jiu'],
        78338 => ['ascii' => 'Targu Carbunesti', 'display' => 'Târgu Cărbunești'],
        78463 => ['ascii' => 'Ticleni', 'display' => 'Țicleni'],
        83641 => ['ascii' => 'Toplita', 'display' => 'Toplița'],
        83437 => ['ascii' => 'Baile Tusnad', 'display' => 'Băile Tușnad'],
        83473 => ['ascii' => 'Balan', 'display' => 'Bălan'],
        83758 => ['ascii' => 'Vlahita', 'display' => 'Vlăhița'],
        87647 => ['ascii' => 'Orastie', 'display' => 'Orăștie'],
        87004 => ['ascii' => 'Petrosani', 'display' => 'Petroșani'],
        87433 => ['ascii' => 'Calan', 'display' => 'Călan'],
        87585 => ['ascii' => 'Hateg', 'display' => 'Hațeg'],
        92710 => ['ascii' => 'Fetesti', 'display' => 'Fetești'],
        93076 => ['ascii' => 'Cazanesti', 'display' => 'Căzănești'],
        102758 => ['ascii' => 'Fierbinti-Targ', 'display' => 'Fierbinți-Târg'],
        92774 => ['ascii' => 'Tandarei', 'display' => 'Țăndărei'],
        95079 => ['ascii' => 'Iasi', 'display' => 'Iași'],
        95408 => ['ascii' => 'Pascani', 'display' => 'Pașcani'],
        95364 => ['ascii' => 'Harlau', 'display' => 'Hârlău'],
        95480 => ['ascii' => 'Targu Frumos', 'display' => 'Târgu Frumos'],
        179418 => ['ascii' => 'Magurele', 'display' => 'Măgurele'],
        179542 => ['ascii' => 'Popesti-Leordeni', 'display' => 'Popești-Leordeni'],
        106568 => ['ascii' => 'Sighetu Marmatiei', 'display' => 'Sighetu Marmației'],
        106755 => ['ascii' => 'Borsa', 'display' => 'Borșa'],
        108026 => ['ascii' => 'Dragomiresti', 'display' => 'Dragomirești'],
        108909 => ['ascii' => 'Salistea de Sus', 'display' => 'Săliștea de Sus'],
        109185 => ['ascii' => 'Somcuta Mare', 'display' => 'Șomcuta Mare'],
        106826 => ['ascii' => 'Targu Lapus', 'display' => 'Târgu Lăpuș'],
        106470 => ['ascii' => 'Tautii-Magheraus', 'display' => 'Tăuții-Măgherăuș'],
        106988 => ['ascii' => 'Viseu de Sus', 'display' => 'Vișeu de Sus'],
        110072 => ['ascii' => 'Orsova', 'display' => 'Orșova'],
        109933 => ['ascii' => 'Baia de Arama', 'display' => 'Baia de Aramă'],
        110241 => ['ascii' => 'Vanju Mare', 'display' => 'Vânju Mare'],
        114523 => ['ascii' => 'Sighisoara', 'display' => 'Sighișoara'],
        114328 => ['ascii' => 'Targu Mures', 'display' => 'Târgu Mureș'],
        114934 => ['ascii' => 'Tarnaveni', 'display' => 'Târnăveni'],
        114729 => ['ascii' => 'Ludus', 'display' => 'Luduș'],
        119340 => ['ascii' => 'Sangeorgiu de Padure', 'display' => 'Sângeorgiu de Pădure'],
        119251 => ['ascii' => 'Sarmasu', 'display' => 'Sărmașu'],
        120735 => ['ascii' => 'Piatra Neamt', 'display' => 'Piatra Neamț'],
        121064 => ['ascii' => 'Targu Neamt', 'display' => 'Târgu Neamț'],
        125427 => ['ascii' => 'Bals', 'display' => 'Balș'],
        125631 => ['ascii' => 'Draganesti-Olt', 'display' => 'Drăgănești-Olt'],
        128720 => ['ascii' => 'Scornicesti', 'display' => 'Scornicești'],
        131265 => ['ascii' => 'Campina', 'display' => 'Câmpina'],
        130543 => ['ascii' => 'Ploiesti', 'display' => 'Ploiești'],
        130990 => ['ascii' => 'Baicoi', 'display' => 'Băicoi'],
        131078 => ['ascii' => 'Boldesti-Scaeni', 'display' => 'Boldești-Scăeni'],
        131229 => ['ascii' => 'Busteni', 'display' => 'Bușteni'],
        131586 => ['ascii' => 'Slanic', 'display' => 'Slănic'],
        131639 => ['ascii' => 'Urlati', 'display' => 'Urlați'],
        131826 => ['ascii' => 'Valenii de Munte', 'display' => 'Vălenii de Munte'],
        136606 => ['ascii' => 'Negresti-Oas', 'display' => 'Negrești-Oaș'],
        136651 => ['ascii' => 'Tasnad', 'display' => 'Tășnad'],
        139713 => ['ascii' => 'Zalau', 'display' => 'Zalău'],
        139893 => ['ascii' => 'Simleu Silvaniei', 'display' => 'Șimleu Silvaniei'],
        143628 => ['ascii' => 'Medias', 'display' => 'Mediaș'],
        143744 => ['ascii' => 'Cisnadie', 'display' => 'Cisnădie'],
        143780 => ['ascii' => 'Copsa Mica', 'display' => 'Copșa Mică'],
        143815 => ['ascii' => 'Dumbraveni', 'display' => 'Dumbrăveni'],
        145505 => ['ascii' => 'Saliste', 'display' => 'Săliște'],
        145836 => ['ascii' => 'Talmaciu', 'display' => 'Tălmaciu'],
        146511 => ['ascii' => 'Campulung Moldovenesc', 'display' => 'Câmpulung Moldovenesc'],
        146548 => ['ascii' => 'Falticeni', 'display' => 'Fălticeni'],
        146637 => ['ascii' => 'Radauti', 'display' => 'Rădăuți'],
        147367 => ['ascii' => 'Brosteni', 'display' => 'Broșteni'],
        146986 => ['ascii' => 'Milisauti', 'display' => 'Milișăuți'],
        151889 => ['ascii' => 'Rosiorii de Vede', 'display' => 'Roșiorii de Vede'],
        151692 => ['ascii' => 'Turnu Magurele', 'display' => 'Turnu Măgurele'],
        155252 => ['ascii' => 'Timisoara', 'display' => 'Timișoara'],
        155412 => ['ascii' => 'Buzias', 'display' => 'Buziaș'],
        156810 => ['ascii' => 'Faget', 'display' => 'Făget'],
        157095 => ['ascii' => 'Gataia', 'display' => 'Gătaia'],
        158323 => ['ascii' => 'Recas', 'display' => 'Recaș'],
        155537 => ['ascii' => 'Sannicolau Mare', 'display' => 'Sânnicolau Mare'],
        159749 => ['ascii' => 'Macin', 'display' => 'Măcin'],
        161801 => ['ascii' => 'Barlad', 'display' => 'Bârlad'],
        161838 => ['ascii' => 'Husi', 'display' => 'Huși'],
        161865 => ['ascii' => 'Negresti', 'display' => 'Negrești'],
        167990 => ['ascii' => 'Dragasani', 'display' => 'Drăgășani'],
        167482 => ['ascii' => 'Ramnicu Valcea', 'display' => 'Râmnicu Vâlcea'],
        168381 => ['ascii' => 'Babeni', 'display' => 'Băbeni'],
        168176 => ['ascii' => 'Baile Govora', 'display' => 'Băile Govora'],
        167730 => ['ascii' => 'Baile Olanesti', 'display' => 'Băile Olănești'],
        168461 => ['ascii' => 'Balcesti', 'display' => 'Bălcești'],
        168611 => ['ascii' => 'Berbesti', 'display' => 'Berbești'],
        167918 => ['ascii' => 'Calimanesti', 'display' => 'Călimănești'],
        174753 => ['ascii' => 'Focsani', 'display' => 'Focșani'],
        174931 => ['ascii' => 'Marasesti', 'display' => 'Mărășești'],
        175028 => ['ascii' => 'Odobesti', 'display' => 'Odobești'],
    ];

    public static function displayName(int $sirutaCode, string $fallback): string
    {
        return self::NAMES[$sirutaCode]['display'] ?? $fallback;
    }

    public static function asciiName(int $sirutaCode, string $fallback): string
    {
        return self::NAMES[$sirutaCode]['ascii'] ?? $fallback;
    }

    public static function displayNames(): array
    {
        return array_map(fn (array $name): string => $name['display'], self::NAMES);
    }

    public static function asciiNames(): array
    {
        return array_map(fn (array $name): string => $name['ascii'], self::NAMES);
    }
}
